FROM cskulab/isolate-with-compilers:v1.1.1

ARG TARGETARCH

RUN apt update && apt install -y wget

RUN if [ "$TARGETARCH" = "amd64" ]; then \
  GO_ARCH="amd64"; \
  elif [ "$TARGETARCH" = "arm64" ]; then \
  GO_ARCH="arm64"; \
  else \
  echo "Unsupported architecture: $TARGETARCH" && exit 1; \
  fi && \
  wget https://go.dev/dl/go1.25.5.linux-${GO_ARCH}.tar.gz && \
  rm -rf /usr/local/go && \
  tar -C /usr/local -xzf go1.25.5.linux-${GO_ARCH}.tar.gz && \
  rm go1.25.5.linux-${GO_ARCH}.tar.gz

ENV PATH="/usr/local/go/bin:/root/go/bin:${PATH}"

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

ENTRYPOINT ["air", "-c", "./docker/worker/.air.toml"]
