FROM cskulab/isolate-with-compilers


RUN apt update && apt install -y wget


RUN wget https://go.dev/dl/go1.25.5.linux-amd64.tar.gz


RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go1.25.5.linux-amd64.tar.gz


ENV PATH="/usr/local/go/bin:/root/go/bin:${PATH}"


RUN go install github.com/air-verse/air@latest

WORKDIR /app


# Copy go.mod and go.sum first to leverage Docker cache
COPY go.mod go.sum ./
RUN go mod download


ENTRYPOINT ["air", "-c", "./docker/worker/.air.toml"]
