// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: config/v1/config.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLanguagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Languages     []*Language            `protobuf:"bytes,1,rep,name=languages,proto3" json:"languages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLanguagesResponse) Reset() {
	*x = GetLanguagesResponse{}
	mi := &file_config_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLanguagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLanguagesResponse) ProtoMessage() {}

func (x *GetLanguagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLanguagesResponse.ProtoReflect.Descriptor instead.
func (*GetLanguagesResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *GetLanguagesResponse) GetLanguages() []*Language {
	if x != nil {
		return x.Languages
	}
	return nil
}

type GetLanguagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeName    bool                   `protobuf:"varint,1,opt,name=include_name,json=includeName,proto3" json:"include_name,omitempty"`
	IncludeVersion bool                   `protobuf:"varint,2,opt,name=include_version,json=includeVersion,proto3" json:"include_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetLanguagesRequest) Reset() {
	*x = GetLanguagesRequest{}
	mi := &file_config_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLanguagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLanguagesRequest) ProtoMessage() {}

func (x *GetLanguagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLanguagesRequest.ProtoReflect.Descriptor instead.
func (*GetLanguagesRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *GetLanguagesRequest) GetIncludeName() bool {
	if x != nil {
		return x.IncludeName
	}
	return false
}

func (x *GetLanguagesRequest) GetIncludeVersion() bool {
	if x != nil {
		return x.IncludeVersion
	}
	return false
}

type GetLanguageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeName    bool                   `protobuf:"varint,1,opt,name=include_name,json=includeName,proto3" json:"include_name,omitempty"`
	IncludeVersion bool                   `protobuf:"varint,2,opt,name=include_version,json=includeVersion,proto3" json:"include_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetLanguageRequest) Reset() {
	*x = GetLanguageRequest{}
	mi := &file_config_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLanguageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLanguageRequest) ProtoMessage() {}

func (x *GetLanguageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLanguageRequest.ProtoReflect.Descriptor instead.
func (*GetLanguageRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *GetLanguageRequest) GetIncludeName() bool {
	if x != nil {
		return x.IncludeName
	}
	return false
}

func (x *GetLanguageRequest) GetIncludeVersion() bool {
	if x != nil {
		return x.IncludeVersion
	}
	return false
}

type Language struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Version       *string                `protobuf:"bytes,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	BuildScript   string                 `protobuf:"bytes,4,opt,name=build_script,json=buildScript,proto3" json:"build_script,omitempty"`
	RunScript     string                 `protobuf:"bytes,5,opt,name=run_script,json=runScript,proto3" json:"run_script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Language) Reset() {
	*x = Language{}
	mi := &file_config_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Language) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Language) ProtoMessage() {}

func (x *Language) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Language.ProtoReflect.Descriptor instead.
func (*Language) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *Language) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Language) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Language) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *Language) GetBuildScript() string {
	if x != nil {
		return x.BuildScript
	}
	return ""
}

func (x *Language) GetRunScript() string {
	if x != nil {
		return x.RunScript
	}
	return ""
}

type LanguageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	BuildScript   *string                `protobuf:"bytes,4,opt,name=build_script,json=buildScript,proto3,oneof" json:"build_script,omitempty"`
	RunScript     string                 `protobuf:"bytes,5,opt,name=run_script,json=runScript,proto3" json:"run_script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LanguageResponse) Reset() {
	*x = LanguageResponse{}
	mi := &file_config_v1_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LanguageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguageResponse) ProtoMessage() {}

func (x *LanguageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguageResponse.ProtoReflect.Descriptor instead.
func (*LanguageResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{4}
}

func (x *LanguageResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LanguageResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LanguageResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *LanguageResponse) GetBuildScript() string {
	if x != nil && x.BuildScript != nil {
		return *x.BuildScript
	}
	return ""
}

func (x *LanguageResponse) GetRunScript() string {
	if x != nil {
		return x.RunScript
	}
	return ""
}

type AddLanguageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	BuildScript   *string                `protobuf:"bytes,3,opt,name=build_script,json=buildScript,proto3,oneof" json:"build_script,omitempty"`
	RunScript     string                 `protobuf:"bytes,4,opt,name=run_script,json=runScript,proto3" json:"run_script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLanguageRequest) Reset() {
	*x = AddLanguageRequest{}
	mi := &file_config_v1_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLanguageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLanguageRequest) ProtoMessage() {}

func (x *AddLanguageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLanguageRequest.ProtoReflect.Descriptor instead.
func (*AddLanguageRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{5}
}

func (x *AddLanguageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddLanguageRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AddLanguageRequest) GetBuildScript() string {
	if x != nil && x.BuildScript != nil {
		return *x.BuildScript
	}
	return ""
}

func (x *AddLanguageRequest) GetRunScript() string {
	if x != nil {
		return x.RunScript
	}
	return ""
}

type UpdateLanguageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Version       *string                `protobuf:"bytes,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	BuildScript   *string                `protobuf:"bytes,4,opt,name=build_script,json=buildScript,proto3,oneof" json:"build_script,omitempty"`
	RunScript     *string                `protobuf:"bytes,5,opt,name=run_script,json=runScript,proto3,oneof" json:"run_script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLanguageRequest) Reset() {
	*x = UpdateLanguageRequest{}
	mi := &file_config_v1_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLanguageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLanguageRequest) ProtoMessage() {}

func (x *UpdateLanguageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLanguageRequest.ProtoReflect.Descriptor instead.
func (*UpdateLanguageRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateLanguageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLanguageRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateLanguageRequest) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *UpdateLanguageRequest) GetBuildScript() string {
	if x != nil && x.BuildScript != nil {
		return *x.BuildScript
	}
	return ""
}

func (x *UpdateLanguageRequest) GetRunScript() string {
	if x != nil && x.RunScript != nil {
		return *x.RunScript
	}
	return ""
}

type DeleteLanguageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLanguageRequest) Reset() {
	*x = DeleteLanguageRequest{}
	mi := &file_config_v1_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLanguageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLanguageRequest) ProtoMessage() {}

func (x *DeleteLanguageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLanguageRequest.ProtoReflect.Descriptor instead.
func (*DeleteLanguageRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteLanguageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_config_v1_config_proto protoreflect.FileDescriptor

const file_config_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x16config/v1/config.proto\x12\tconfig.v1\x1a\x1bgoogle/protobuf/empty.proto\"I\n" +
	"\x14GetLanguagesResponse\x121\n" +
	"\tlanguages\x18\x01 \x03(\v2\x13.config.v1.LanguageR\tlanguages\"a\n" +
	"\x13GetLanguagesRequest\x12!\n" +
	"\finclude_name\x18\x01 \x01(\bR\vincludeName\x12'\n" +
	"\x0finclude_version\x18\x02 \x01(\bR\x0eincludeVersion\"`\n" +
	"\x12GetLanguageRequest\x12!\n" +
	"\finclude_name\x18\x01 \x01(\bR\vincludeName\x12'\n" +
	"\x0finclude_version\x18\x02 \x01(\bR\x0eincludeVersion\"\xa9\x01\n" +
	"\bLanguage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\tH\x01R\aversion\x88\x01\x01\x12!\n" +
	"\fbuild_script\x18\x04 \x01(\tR\vbuildScript\x12\x1d\n" +
	"\n" +
	"run_script\x18\x05 \x01(\tR\trunScriptB\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_version\"\xa8\x01\n" +
	"\x10LanguageResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12&\n" +
	"\fbuild_script\x18\x04 \x01(\tH\x00R\vbuildScript\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"run_script\x18\x05 \x01(\tR\trunScriptB\x0f\n" +
	"\r_build_script\"\x9a\x01\n" +
	"\x12AddLanguageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12&\n" +
	"\fbuild_script\x18\x03 \x01(\tH\x00R\vbuildScript\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"run_script\x18\x04 \x01(\tR\trunScriptB\x0f\n" +
	"\r_build_script\"\xe0\x01\n" +
	"\x15UpdateLanguageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\tH\x01R\aversion\x88\x01\x01\x12&\n" +
	"\fbuild_script\x18\x04 \x01(\tH\x02R\vbuildScript\x88\x01\x01\x12\"\n" +
	"\n" +
	"run_script\x18\x05 \x01(\tH\x03R\trunScript\x88\x01\x01B\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_versionB\x0f\n" +
	"\r_build_scriptB\r\n" +
	"\v_run_script\"'\n" +
	"\x15DeleteLanguageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x9d\x03\n" +
	"\rConfigService\x12Q\n" +
	"\fGetLanguages\x12\x1e.config.v1.GetLanguagesRequest\x1a\x1f.config.v1.GetLanguagesResponse\"\x00\x12K\n" +
	"\vGetLanguage\x12\x1d.config.v1.GetLanguageRequest\x1a\x1b.config.v1.LanguageResponse\"\x00\x12K\n" +
	"\vAddLanguage\x12\x1d.config.v1.AddLanguageRequest\x1a\x1b.config.v1.LanguageResponse\"\x00\x12Q\n" +
	"\x0eUpdateLanguage\x12 .config.v1.UpdateLanguageRequest\x1a\x1b.config.v1.LanguageResponse\"\x00\x12L\n" +
	"\x0eDeleteLanguage\x12 .config.v1.DeleteLanguageRequest\x1a\x16.google.protobuf.Empty\"\x00B\x93\x01\n" +
	"\rcom.config.v1B\vConfigProtoP\x01Z0github.com/CSKU-Lab/config-server/grpc/config/v1\xa2\x02\x03CXX\xaa\x02\tConfig.V1\xca\x02\tConfig\\V1\xe2\x02\x15Config\\V1\\GPBMetadata\xea\x02\n" +
	"Config::V1b\x06proto3"

var (
	file_config_v1_config_proto_rawDescOnce sync.Once
	file_config_v1_config_proto_rawDescData []byte
)

func file_config_v1_config_proto_rawDescGZIP() []byte {
	file_config_v1_config_proto_rawDescOnce.Do(func() {
		file_config_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_v1_config_proto_rawDesc), len(file_config_v1_config_proto_rawDesc)))
	})
	return file_config_v1_config_proto_rawDescData
}

var file_config_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_config_v1_config_proto_goTypes = []any{
	(*GetLanguagesResponse)(nil),  // 0: config.v1.GetLanguagesResponse
	(*GetLanguagesRequest)(nil),   // 1: config.v1.GetLanguagesRequest
	(*GetLanguageRequest)(nil),    // 2: config.v1.GetLanguageRequest
	(*Language)(nil),              // 3: config.v1.Language
	(*LanguageResponse)(nil),      // 4: config.v1.LanguageResponse
	(*AddLanguageRequest)(nil),    // 5: config.v1.AddLanguageRequest
	(*UpdateLanguageRequest)(nil), // 6: config.v1.UpdateLanguageRequest
	(*DeleteLanguageRequest)(nil), // 7: config.v1.DeleteLanguageRequest
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_config_v1_config_proto_depIdxs = []int32{
	3, // 0: config.v1.GetLanguagesResponse.languages:type_name -> config.v1.Language
	1, // 1: config.v1.ConfigService.GetLanguages:input_type -> config.v1.GetLanguagesRequest
	2, // 2: config.v1.ConfigService.GetLanguage:input_type -> config.v1.GetLanguageRequest
	5, // 3: config.v1.ConfigService.AddLanguage:input_type -> config.v1.AddLanguageRequest
	6, // 4: config.v1.ConfigService.UpdateLanguage:input_type -> config.v1.UpdateLanguageRequest
	7, // 5: config.v1.ConfigService.DeleteLanguage:input_type -> config.v1.DeleteLanguageRequest
	0, // 6: config.v1.ConfigService.GetLanguages:output_type -> config.v1.GetLanguagesResponse
	4, // 7: config.v1.ConfigService.GetLanguage:output_type -> config.v1.LanguageResponse
	4, // 8: config.v1.ConfigService.AddLanguage:output_type -> config.v1.LanguageResponse
	4, // 9: config.v1.ConfigService.UpdateLanguage:output_type -> config.v1.LanguageResponse
	8, // 10: config.v1.ConfigService.DeleteLanguage:output_type -> google.protobuf.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_config_v1_config_proto_init() }
func file_config_v1_config_proto_init() {
	if File_config_v1_config_proto != nil {
		return
	}
	file_config_v1_config_proto_msgTypes[3].OneofWrappers = []any{}
	file_config_v1_config_proto_msgTypes[4].OneofWrappers = []any{}
	file_config_v1_config_proto_msgTypes[5].OneofWrappers = []any{}
	file_config_v1_config_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_v1_config_proto_rawDesc), len(file_config_v1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_v1_config_proto_goTypes,
		DependencyIndexes: file_config_v1_config_proto_depIdxs,
		MessageInfos:      file_config_v1_config_proto_msgTypes,
	}.Build()
	File_config_v1_config_proto = out.File
	file_config_v1_config_proto_goTypes = nil
	file_config_v1_config_proto_depIdxs = nil
}
