name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    uses: CSKU-Lab/.github/.github/workflows/docker-publish.yml@main
    with:
      image_name: go-grader-master
      dockerfile_path: docker/master/Dockerfile
      secondary_image_name: go-grader-worker
      secondary_dockerfile_path: docker/worker/Dockerfile
      gitops_paths: apps/go-grader-master/env.libsonnet apps/go-grader-worker/env.libsonnet
      service_name: go-grader
    secrets: inherit
